@startuml ttt


S0Fetch --> S1Decode : [*]
S0Fetch : [IRWrite = 1]
S0Fetch : [AdrSrc = 0]

S0Fetch : [ALUOp = 00]
S0Fetch : [ALUSrcA = 00]
S0Fetch : [ALUSrcB = 10]
S0Fetch : [ResultSrc = 10]
S0Fetch : [MemWrite = 0]
S0Fetch : [RegWrite = 0]
S0Fetch : [PCWrite = 1]






S1Decode --> S2MemAdr : [0000011 | 0100011]
S1Decode : [IRWrite = 0]
S1Decode : [AdrSrc = 0]
S1Decode : [ALUOp = 00]
S1Decode : [ALUSrcA = 00]
S1Decode : [ALUSrcB = 00]
S1Decode : [ResultSrc = 00]
S1Decode : [MemWrite = 0]
S1Decode : [RegWrite = 0]
S1Decode : [PCWrite = 0]



S2MemAdr --> S3MemRead : [0000011]
S2MemAdr --> S5MemWrite : [0100011]
S2MemAdr : [ALUOp = 00]
S2MemAdr : [ALUSrcA = 10]
S2MemAdr : [ALUSrcB = 01]

S2MemAdr : [IRWrite = 0]
S2MemAdr : [AdrSrc = 0]
S2MemAdr : [ResultSrc = 00]
S2MemAdr : [MemWrite = 0]
S2MemAdr : [RegWrite = 0]
S2MemAdr : [PCWrite = 0]



S3MemRead --> S4MemWB : [*]
S3MemRead : [ResultSrc = 00]
S3MemRead : [AdrSrc = 1]
S3MemRead : [IRWrite = 0]
S3MemRead : [ALUOp = 00]
S3MemRead : [ALUSrcA = 00]
S3MemRead : [ALUSrcB = 00]
S3MemRead : [MemWrite = 0]
S3MemRead : [RegWrite = 0]
S3MemRead : [PCWrite = 0]






S5MemWrite --> S0Fetch : [*]
S5MemWrite : [ResultSrc = 00]
S5MemWrite : [AdrSrc = 1]
S5MemWrite : [MemWrite = 1]

S5MemWrite : [IRWrite = 0]
S5MemWrite : [ALUOp = 00]
S5MemWrite : [ALUSrcA = 00]
S5MemWrite : [ALUSrcB = 00]
S5MemWrite : [RegWrite = 0]
S5MemWrite : [PCWrite = 0]



S4MemWB --> S0Fetch : [*]
S4MemWB : [ResultSrc = 01]
S4MemWB : [RegWrite = 1]



S4MemWB : [IRWrite = 0]
S4MemWB : [AdrSrc = 0]
S4MemWB : [ALUOp = 00]
S4MemWB : [ALUSrcA = 00]
S4MemWB : [ALUSrcB = 00]
S4MemWB : [MemWrite = 0]
S4MemWB : [PCWrite = 0]
@enduml